Correct TinyEmitter's types - Fixes #29
scottcorgan/tiny-emitter pull request #30
Opened 2018-02-22 20:47 UTC by MadaraUchiha

- Add .TinyEmitter to module.exports exposing E from that key.
- Remove the faulty ability to `import * as TinyEmitter` in TypeScript
- Add the ability to `import { TinyEmitter }` in TypeScript
- Change all method return types to return `this` instead of
  `TinyEmitter`, this way, extending classes would have correct return
  types.

2018-02-26 13:59 UTC, scottcorgan requested changes
This looks great. Can you get rid of the spaces between function name and parenthesis diffs? I'd like to keep this PR small and to the point. Thanks!

2018-03-13 14:30 UTC, scottcorgan approved these changes

2018-03-13 14:31 UTC, merged

2018-06-21 02:08 UTC, jakemmarsh commented
Any updates on publishing this @scottcorgan?

2018-12-03 06:38 UTC, Dan503 commented
Can this please be published to npm?